"""Initial migration

Revision ID: 5d781d9dd2f9
Revises: 
Create Date: 2024-02-15 19:32:18.681337

"""
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d781d9dd2f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db_file_path = "/recipes.db"

    if os.path.exists(db_file_path):
        os.remove(db_file_path)
    # ### end Alembic commands ###
