"""Added relationships

Revision ID: a16698023163
Revises: 9bc2ec5484a1
Create Date: 2024-02-16 09:48:29.274441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16698023163'
down_revision = '9bc2ec5484a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'recipes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'author_id')
    op.drop_column('recipes', 'category_id')
    # ### end Alembic commands ###
